name: HelloDart

version: 1.2.3
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  args: ^2.3.0
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0


  dev_dependencies:
14   lints: ^1.0.1
 